version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: horarios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data  # ✅ solo lo necesario

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  dbdata:
