"""migración inicial completa

Revision ID: 20cc8d5097a7
Revises: 
Create Date: 2025-05-19 23:52:45.487250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20cc8d5097a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facultades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_facultades_id'), 'facultades', ['id'], unique=False)
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('numero_empleado', sa.String(length=20), nullable=False),
    sa.Column('facultad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facultad_id'], ['facultades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('numero_empleado')
    )
    op.create_index(op.f('ix_docentes_id'), 'docentes', ['id'], unique=False)
    op.create_table('planes_estudio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('facultad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facultad_id'], ['facultades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_estudio_id'), 'planes_estudio', ['id'], unique=False)
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('plan_estudio_id', sa.Integer(), nullable=False),
    sa.Column('permite_superposicion', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plan_estudio_id'], ['planes_estudio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_materias_id'), 'materias', ['id'], unique=False)
    op.create_table('asignaciones_materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('docente_id', 'materia_id', name='uix_docente_materia')
    )
    op.create_index(op.f('ix_asignaciones_materia_id'), 'asignaciones_materia', ['id'], unique=False)
    op.create_table('clases_programadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.Column('aula', sa.String(), nullable=False),
    sa.Column('dia', sa.Enum('lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo', name='diasemanaenum'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clases_programadas_id'), 'clases_programadas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clases_programadas_id'), table_name='clases_programadas')
    op.drop_table('clases_programadas')
    op.drop_index(op.f('ix_asignaciones_materia_id'), table_name='asignaciones_materia')
    op.drop_table('asignaciones_materia')
    op.drop_index(op.f('ix_materias_id'), table_name='materias')
    op.drop_table('materias')
    op.drop_index(op.f('ix_planes_estudio_id'), table_name='planes_estudio')
    op.drop_table('planes_estudio')
    op.drop_index(op.f('ix_docentes_id'), table_name='docentes')
    op.drop_table('docentes')
    op.drop_index(op.f('ix_facultades_id'), table_name='facultades')
    op.drop_table('facultades')
    # ### end Alembic commands ###
